repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.3
  hooks:
    # Run the linter.
    - id: ruff
      entry: poetry run ruff check
      args: [ --fix ]

    - id: ruff-format
      entry: poetry run ruff format
